version: "2"
plugins:
  duplication:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core"
checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
    enabled: false
  method-complexity:
    enabled: false
exclude_patterns:
  - "admin/js/**/tipso*"
  - ".dev/tests/"
  - "Gruntfile.js"
